### ISSUE TITLE
where is the code?

### ISSUE THREAD

**Issue by phra** [zkat/node-otp#1]
i'm looking at OTP in these days and i want to make some experiments with nodejs but i don't see any existing project on github so i'm wondering why. maybe implementing the erlang scheduler is not possible without change nodejs itself?

thanks for the infos.

**Comment by zkat** [comment]
Oh. Nah, I can probably implement this in node. I just never got around to it. I'm sure there's other projects that have done similar :)

**Comment by phra** [comment]
i've looked at [node-fibers](https://github.com/laverdet/node-fibers) but i'm not sure that it can manage all the erlang/otp use cases.
btw i'm looking towards to make some experiments with it to understand if it fits to solve the problem.
my biggest doubts atm are implementing `green threads` concept of erlang vm in v8 vm, implementing the erlang vm scheduler and `per-process` garbage collector needed to have good performance in higly concurrent and distributed systems.

which other projects do you know that are trying to implement otp in js/v8? i haven't found nothing yet.

**Comment by zkat** [comment]
I don't know of any right now, sorry. But I'm sure searching npm or googling might yield interesting results?
